name: Deploy to test

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app to test
    runs-on: ubuntu-latest

    environment:
      name: test
      url: https://carterjohns.com/app-test/

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Confirm destination
        run: echo "Deploying to ${{ vars.DEPLOY_PATH }}"